### PR TITLE
Adding command to extract a set of .rar archives

### PR DESCRIPTION
**Pull request by SplinterHead**
This is pulled from my aliases file and works great there

### CODE REVIEW

**Review by melancholySheep02 — COMMENTED** [review]
Hi @SplinterHead ,
Is this script tested ?
I am getting the error "find: missing argument to `-exec'" on executing the script.
I am not much of an expert on shell scripting . so could you please tell what i'm doing wrong here or if this script need fixing ? 
Thanks

**Comment by melancholySheep02** [comment]
also pardon me for the late reply on this PR :p

**Comment by SplinterHead** [comment]
I'll double check that the quote escaping is correct later and recommit

**Review by melancholySheep02 — APPROVED** [review]
Hi @SplinterHead ,
Thanks for the prompt changes done. 
i've checked the changes . and both the scripts (with and without alias) works fine.
i'm merging the PR. 
Thanks for the support .

**Pull request merged**
